name: /Users/geet/Documents/Repositories/Owned/gogoesgone/gogoesgone_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray=2023.3
  - matplotlib
  - seaborn
  - numpy
  - tqdm
  - ca-certificates
  - openssl
  - ipykernel
  - certifi
  - netcdf4
  - cartopy
  - kerchunk
  - metpy
  - s3fs
  - h5py
  - dask
  - pip
  - pip:
        - -e .
prefix: /Users/geet/Documents/Repositories/Owned/goesdata/goesdata_env
